cmake -GNinja -H./llvm-project/llvm -B/tmp/llvm-project-build-stage1 \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_PROJECTS="clang;lld" \
    -DLLVM_TARGETS_TO_BUILD="X86;AArch64" \
    -DLLVM_BUILD_TOOLS=false \
    -DLLVM_INCLUDE_TESTS=false \
    -DLLVM_INCLUDE_BENCHMARKS=false \
    -DLLVM_APPEND_VC_REV=false \
    -DLLVM_CCACHE_BUILD=true \
    -DLLVM_USE_LINKER=gold \
    -DLLVM_BINUTILS_INCDIR=/usr/include \
    -DCLANG_ENABLE_ARCMT=false \
    -DCLANG_ENABLE_STATIC_ANALYZER=false
